inputs:
#  arduino_ide_version:
#        description: "Arduino IDE version"
#       default: "1.8.13"
#        type: string
  board:
    description: "Board to install"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Install uf2
      shell: bash
      run: |
        echo "Install uf2"
        git clone https://github.com/microsoft/uf2 ~/uf2

    - name: Install Arduino for ${{ inputs.board }}
      shell: bash
      run: |
        echo "Install Arduino for ${{ inputs.board }}"
        mkdir -p ~/.local/bin
        # version 0.28.0 gave me issues so fixed fot 0.27.1 for now
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh -s 0.27.1

    - name: Install platform python nrfutil
      shell: bash
      run: |
        echo "Install board nrfutil"
        if [[ "${{ inputs.board }}" =~ "adafruit:nrf52:" ]]; then
          sudo apt-get install python3-pip
          pip3 install setuptools --user
          pip3 install adafruit-nrfutil --user
          pip3 install intelhex --user
        fi
