# This is a basic workflow to help you get started with Actions

name: SoftRF Stratux build environment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on:
  workflow_call:
    inputs:
      arduino_ide_version:
#        description: "Arduino IDE version"
#       default: "1.8.13"
#        type: string
      board:
        description: "Board to install"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
#      ARDUINO_IDE_VERSION: ${{ inputs.arduino_ide_version }}
      BOARD: ${{ inputs.board }}

    steps:
      # Runs a set of commands using the runners shell
      - name: Download and install Arduino for ${{ inputs.board }}
        run: |
          git clone https://github.com/microsoft/uf2 ~/uf2
          mkdir -p ~/.local/bin
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh
          if [[ "$BOARD" =~ "adafruit:nrf52:" ]]; then
            sudo apt-get install python3-pip
            pip3 install setuptools --user
            pip3 install adafruit-nrfutil --user
            pip3 install intelhex --user
          fi

      - name: Install needed board ${{ inputs.board }}
        run: |
          mkdir $HOME/Arduino
          ln -s $GITHUB_WORKSPACE/software/firmware/source/libraries $HOME/Arduino/libraries
          
          if [[ "$BOARD" =~ "esp32:esp32" ]]; then
            arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          fi

          if [[ "$BOARD" =~ "adafruit:nrf52:" ]]; then
            arduino-cli core install adafruit:nrf52 --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
            if [[ ! -f ~/.local/bin/adafruit-nrfutil ]]; then
              ln -s /bin/true ~/.local/bin/adafruit-nrfutil
            fi
          fi
          cd $GITHUB_WORKSPACE
