name: CI CD Pipeline

on:
  push:
    branches:
      - master
      - arduino-cli

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - 'esp32:esp32:esp32:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashFreq=80,FlashMode=dio,FlashSize=4M,DebugLevel=none'
          - 'adafruit:nrf52:pca10056'
          - 'esp32:esp32:esp32s2:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashMode=dio,FlashSize=4M,DebugLevel=none'
          - 'esp32:esp32:esp32s3:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashMode=dio,FlashSize=4M,DebugLevel=none'
    env:
      BOARD: ${{ matrix.board }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/build-environment
        with:
          board: ${{ matrix.board }}

      - name: Run script
        shell: bash
        run: |
          export BOARD=${{ matrix.board }}
          echo 'Building board ${BOARD}'
          arduino-cli compile -e -b $BOARD $GITHUB_WORKSPACE/software/firmware/source/SoftRF
          PART1=$(cut -d':' -f1 <<< $BOARD)
          PART2=$(cut -d':' -f2 <<< $BOARD)
          PART3=$(cut -d':' -f3 <<< $BOARD)
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/$PART1.$PART2.$PART3"
          
          if [[ "$BOARD" =~ "esp32:esp32:"        ]]; then
            zip -r "SoftRF_$PART3".zip . 
          fi ;
          
          if [[ "$BOARD" =~ "adafruit:nrf52:"        ]]; then
            ~/uf2/utils/uf2conv.py SoftRF.ino.hex -c -f 0xADA52840
            mv SoftRF.ino.zip SoftRF_$PART3.zip
          fi ;
          
          find .
          cd "$GITHUB_WORKSPACE"

      - uses: actions/upload-artifact@v3
        with:
          name: SoftRF_$PART3.zip
          path: "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/**/*.zip"
          if-no-files-found: error

  release:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    uses: rvt/SoftRF/.github/workflows/ci-release.yml@arduino-cli
    with:
      myName: "monaWeb 4"
      envName: true

