name: CI CD Pipeline

on:
  push:
    branches:
      - master
      - prerelease

  workflow_dispatch:

#permissions:
#  contents: read
#  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board: 'esp32:esp32:esp32:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashFreq=80,FlashMode=dio,FlashSize=4M,DebugLevel=none'
            artifact: 'SoftRF-esp32'
            path: 'esp32.esp32.esp32'
          - board: 'adafruit:nrf52:pca10056'
            artifact: 'SoftRF-nrf52'
            path: 'adafruit.nrf52.pca10056'
          - board: 'esp32:esp32:esp32s2:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashMode=dio,FlashSize=4M,DebugLevel=none'
            artifact: 'SoftRF-esp32s'
            path: 'esp32.esp32.esp32s2'
          - board: 'esp32:esp32:esp32s3:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashMode=dio,FlashSize=4M,DebugLevel=none'
            artifact: 'SoftRF-esp32s3'
            path: 'esp32.esp32.esp32s3'

    env:
      ARDUINO_IDE_VERSION: 1.8.13
      BOARD: ${{ matrix.board }}
      ARTIFACT: ${{ matrix.artifact }}

    steps:
      - name: Install rename
        run: sudo apt-get install -y rename

      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-environment
        with:
          board: ${{ matrix.board }}

      - name: Build SoftRF for platform ${{ matrix.board }}
        run: |
          echo 'Building board ${{ matrix.board }}'
          # Get version and compile
          arduino-cli version
          arduino-cli compile -e -b "${{ matrix.board }}" $GITHUB_WORKSPACE/software/firmware/source/SoftRF

      - name: List generated files
        run: |
          find "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/"

      - name: Running uf2
        if: startsWith(matrix.board, 'adafruit:nrf52:')
        run: |
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/${{ matrix.path }}"
          ~/uf2/utils/uf2conv.py SoftRF.ino.hex -c -f 0xADA52840
          mv flash.uf2 SoftRF.uf2
          # Remove files that we do not need for uf2 targets
          shopt -s extglob
          rm -v !("SoftRF.uf2")

      - name: Rename before artifact upload
        run: |
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/${{ matrix.path }}"
          rename -v 's/SoftRF/${{ matrix.artifact }}/' SoftRF*
          ls .

      - uses: actions/upload-artifact@v3
        with:
          name: SoftRF
          path: |
            "${{ github.workspace }}/software/firmware/source/SoftRF/build/${{ matrix.path }}/"
          if-no-files-found: error

  additional:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v3
        with:
          name: additional
          path: |
            STRATUX.md
          if-no-files-found: error

  prerelease:
    if: ${{ startsWith(github.event.ref, 'refs/heads/prerelease') }}
    needs: additional
    uses: rvt/SoftRF/.github/workflows/ci-release.yml@prerelease
    with:
      prerelease: true
      environment: Prerelease
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
    needs: additional
    uses: rvt/SoftRF/.github/workflows/ci-release.yml@prerelease
    with:
      prerelease: false
      environment: Release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
