name: CI CD Pipeline

on:
  push:
    branches:
      - master
      - arduino-cli

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board: 'esp32:esp32:esp32:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashFreq=80,FlashMode=dio,FlashSize=4M,DebugLevel=none'
            artifact: 'SoftRF-esp32'
            path: 'esp32.esp32.esp32'
          - board: 'adafruit:nrf52:pca10056'
            artifact: 'SoftRF-nrf52'
            path: 'adafruit.nrf52.pca10056'
          - board: 'esp32:esp32:esp32s2:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashMode=dio,FlashSize=4M,DebugLevel=none'
            artifact: 'SoftRF-esp32s'
            path: 'esp32.esp32.esp32s2'
          - board: 'esp32:esp32:esp32s3:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashMode=dio,FlashSize=4M,DebugLevel=none'
            artifact: 'SoftRF-esp32s3'
            path: 'esp32.esp32.esp32s3'

    env:
      ARDUINO_IDE_VERSION: 1.8.13
      BOARD: ${{ matrix.board }}
      ARTIFACT: ${{ matrix.artifact }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-environment
        with:
          board: ${{ matrix.board }}

      - name: Build SoftRF for platform ${{ matrix.board }}
        run: |
          echo 'Building board ${{ matrix.board }}'
          # Get version and compile
          arduino-cli version
          arduino-cli compile -e -b "${{ matrix.board }}" $GITHUB_WORKSPACE/software/firmware/source/SoftRF
          find "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/"

      - name: Running uf2
        if: startsWith(matrix.board, 'adafruit:nrf52:')
        run: |
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/${{ matrix.path }}"          
          ~/uf2/utils/uf2conv.py SoftRF.ino.hex -c -f 0xADA52840
          cd "$GITHUB_WORKSPACE"

      - uses: actions/upload-artifact@v3
        if: startsWith(matrix.board, 'adafruit:nrf52:')
        with:
          name: ${{ matrix.artifact }}
          path: "software/firmware/source/SoftRF/build/${{ matrix.path }}/"
          if-no-files-found: error

      - uses: actions/upload-artifact@v3
        if: startsWith(matrix.board, 'esp32:esp32:')
        with:
          name: ${{ matrix.artifact }}
          path: "software/firmware/source/SoftRF/build/${{ matrix.path }}/SoftRF.ino.zip"
          if-no-files-found: error

  release:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    uses: rvt/SoftRF/.github/workflows/ci-release.yml@arduino-cli
    with:
      myName: "monaWeb 4"
      envName: true

