name: Generate Release or Prerelease

on:
  workflow_call:
    inputs:
      prerelease:
        description: "prerelease"
        required: true
        default: true
        type: boolean
      environment:
        description: "environment"
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  release:
    permissions:
      actions: write
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3

      - name: Generate Release SHA
        run: |
          echo ${{ github.sha }} > RELEASE.txt
          find .

      - name: PreRelease
        if: ${{ startsWith(inputs.prerelease, true) }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: prerelease
          name: prerelease
          body_path: STRATUX.md
          token: ${{ secrets.token }}
          files: |
            SoftRF/*.zip
            RELEASE.txt
            additional/STRATUX.md
          draft: true
          prerelease: true

      - name: Release
        if: ${{ startsWith(inputs.prerelease, false) }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: STRATUX.md
          token: ${{ secrets.token }}
          files: |
            artifacts/*.zip
            RELEASE.txt
            STRATUX.md
          draft: false
          prerelease: false
