name: Publish to Azure

# Run on call from other workflow
on:
  workflow_call:
    inputs:
      prerelease:
        description: "prerelease"
        required: true
        default: true
        type: boolean
      environment:
        description: "environment"
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  release:
    permissions:
      actions: write

    environment: ${{ inputs.environment }}

    runs-on: ubuntu-latest

    steps:
      - name: cd
        run: |
          cd "${{ github.workspace }}"

      - uses: actions/download-artifact@v3

      - name: Generate Release SHA
        run: |
          ls .
          echo ${{ github.sha }} > RELEASE.txt
          unzip -o ${{ github.workspace }} text.zip
          ls .

      - name: PreRelease
        if: ${{ startsWith(inputs.prerelease, true) }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: prerelease
          name: prerelease
          body_path: STRATUX.md
          token: ${{ secrets.token }}
          files: |
            *.zip
            RELEASE.txt
            STRATUX.md
          draft: true
          prerelease: true

      - name: Release
        if: ${{ startsWith(inputs.prerelease, false) }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: STRATUX.md
          token: ${{ secrets.token }}
          files: |
            artifacts/*.zip
            RELEASE.txt
            STRATUX.md
          draft: false
          prerelease: false
