name: Publish to Azure

# Run on call from other workflow
on:
  workflow_call:
    inputs:
      prerelease:
        description: "prerelease"
        required: true
        default: true
        type: boolean
      draft:
        description: "draft"
        required: true
        default: true
        type: boolean
      environment:
        description: "environment"
        required: true
        default: true
        type: string

jobs:
  release:
    environment: ${{ inputs.environment }}

    runs-on: ubuntu-latest

    steps:
      - name: Set $GITHUB_WORKSPACE
        run: |
          cd "$GITHUB_WORKSPACE"

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Build
        run: echo ${{ github.sha }} > RELEASE.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: SoftRF Stratux releases
          body_path: ${{ github.workspace }}/STRATUX.md
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            artifacts/*.zip
            Release.txt
            STRATUX.md
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
