name: Publish to Azure

# Run on call from other workflow
on:
  workflow_call:
    inputs:
      prerelease:
        description: "prerelease"
        required: true
        default: true
        type: boolean
      environment:
        description: "environment"
        required: true
        default: true
        type: string
      token:
        description: "environment"
        required: true
        default: true
        type: string

jobs:
  release:
    environment: ${{ inputs.environment }}

    runs-on: ubuntu-latest

    steps:
      - name: Set $GITHUB_WORKSPACE
        run: |
          cd "$GITHUB_WORKSPACE"

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Build
        run: echo ${{ github.sha }} > RELEASE.txt

      - name: PreRelease
        if: ${{ startsWith(inputs.prerelease, true) }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: prerelease
          name: prerelease
          body_path: ${{ github.workspace }}/STRATUX.md
          token: ${{ inputs.token }}
          files: |
            artifacts/*.zip
            RELEASE.txt
            STRATUX.md
          draft: true
          prerelease: true

      - name: Release
        if: ${{ startsWith(inputs.prerelease, false) }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/STRATUX.md
          token: ${{ inputs.token }}
          files: |
            artifacts/*.zip
            RELEASE.txt
            STRATUX.md
          draft: false
          prerelease: false
