name: Publish to Azure

# Run on call from other workflow
on:
  workflow_call:
    inputs:
      prerelease:
        description: "prerelease"
        required: true
        default: true
        type: boolean
      environment:
        description: "environment"
        required: true
        type: string
      workspace:
        description: "workspace"
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  release:
    environment: ${{ inputs.environment }}

    runs-on: ubuntu-latest

    steps:
      - name: cd
        shell: bash
        run: |
          cd "${{ inputs.workspace }}"

      - uses: actions/download-artifact@v3
        with:
          path: ${{ inputs.workspace }}/artifacts

      - name: Build
        run: echo ${{ github.sha }} > ${{ inputs.workspace }}/RELEASE.txt

      - name: ls
        shell: bash
        run: |
          ls -ial

      - name: PreRelease
        if: ${{ startsWith(inputs.prerelease, true) }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: prerelease
          name: prerelease
          body_path: ${{ github.workspace }}/STRATUX.md
          token: ${{ secrets.token }}
          files: |
            ${{ inputs.workspace }}/artifacts/*.zip
            ${{ inputs.workspace }}/RELEASE.txt
            ${{ inputs.workspace }}/STRATUX.md
          draft: true
          prerelease: true

      - name: Release
        if: ${{ startsWith(inputs.prerelease, false) }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/STRATUX.md
          token: ${{ secrets.token }}
          files: |
            ${{ inputs.workspace }}/artifacts/*.zip
            ${{ inputs.workspace }}/RELEASE.txt
            ${{ inputs.workspace }}/STRATUX.md
          draft: false
          prerelease: false
