name: Publish to Azure

# Run on call from other workflow
on:
  workflow_call:
    inputs:
      envName:
        description: "Would you like to release?"
        required: true
        default: false
        type: boolean
      myName:
        description: "My Name test"
        required: true
        default: "Some other name"
        type: string

jobs:
  release:
    environment: Release
    name: Deploy to ${{ inputs.myName }}

    runs-on: ubuntu-latest

    steps:
      - name: Set $GITHUB_WORKSPACE
        run: |
          cd "$GITHUB_WORKSPACE"

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
