# This is a basic workflow to help you get started with Actions

name: SoftRF Stratux builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - 'esp32:esp32:esp32:PartitionScheme=min_spiffs,CPUFreq=80,FlashMode=dio,FlashFreq=80,FlashSize=4M,DebugLevel=none'
          - 'adafruit:nrf52:pca10056'
          - 'esp32:esp32:esp32s2'
          - 'esp32:esp32:esp32s3'

    env:
      ARDUINO_IDE_VERSION: 1.8.13
      ENERGIA_IDE_VERSION: 1.8.10E23
      BOARD: ${{ matrix.board }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      # Runs a set of commands using the runners shell
      - name: Run before_install
        run: |
          mkdir -p ~/.local/bin
          git clone https://github.com/microsoft/uf2
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh ;
          if [[ "$BOARD" =~ "adafruit:nrf52:" ]]; then
            sudo apt-get install python3-pip ;
            pip3 install setuptools --user ;
            pip3 install adafruit-nrfutil --user ;
            pip3 install intelhex --user ;
          fi

      - name: Run install
        run: |
          mkdir $HOME/Arduino ;
          ln -s $PWD/software/firmware/source/libraries $HOME/Arduino/libraries ;
          
          if [[ "$BOARD" =~ "esp32:esp32" ]]; then
            arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json ;
            cd $GITHUB_WORKSPACE ;
          fi

          if [[ "$BOARD" =~ "adafruit:nrf52:" ]]; then
            arduino-cli core install adafruit:nrf52 --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json ;
            if [[ ! -f ~/.local/bin/adafruit-nrfutil ]]; then
              ln -s /bin/true ~/.local/bin/adafruit-nrfutil;
            fi ;
            cd $GITHUB_WORKSPACE ;
          fi

      - name: Run script
        run: |
          echo 'Building board ${BOARD}'
          arduino-cli compile -e -b $BOARD $PWD/software/firmware/source/SoftRF ;
          ~/uf2/utils/uf2conv.py $PWD/software/firmware/source/SoftRF/build/adafruit.nrf52.pca10056/SoftRF.ino.hex -c -f 0xADA52840
          ls $PWD/software/firmware/source/SoftRF/build/adafruit.nrf52.pca10056/
