# This is a basic workflow to help you get started with Actions

name: SoftRF Stratux builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: ['esp32:esp32:esp32:PartitionScheme=min_spiffs,CPUFreq=80,FlashMode=dio,FlashFreq=80,FlashSize=4M,DebugLevel=none', 'adafruit:nrf52:pca10056', 'esp32:esp32:esp32s2', 'esp32:esp32:esp32s3']

    env:
      ARDUINO_IDE_VERSION: 1.8.13
      ENERGIA_IDE_VERSION: 1.8.10E23
      BOARD: ${{ matrix.board }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      # Runs a set of commands using the runners shell
      - name: Run before_install
        run: |
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
          sleep 3
          export DISPLAY=:1.0
          mkdir -p ~/.local/bin
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh ;
          if [[ "$BOARD" =~ "adafruit:nrf52:" ]]; then
            sudo apt-get install python3-pip ;
            pip3 install setuptools --user ;
            pip3 install adafruit-nrfutil --user ;
            pip3 install intelhex --user ;
          fi

      - name: Run install
        run: |
          if [[ "$BOARD" =~ "esp32:esp32" ]]; then
            arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json ;
            cd $GITHUB_WORKSPACE ;
          fi

          if [[ "$BOARD" =~ "adafruit:nrf52:" ]]; then
            arduino-cli core install esp32:esp32 --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json ;
            if [[ ! -f ~/.local/bin/adafruit-nrfutil ]]; then
              ln -s /bin/true ~/.local/bin/adafruit-nrfutil;
            fi ;
            cd $GITHUB_WORKSPACE ;
          fi

      - name: Run script
        run: |
          if [[ "$BOARD" =~ "esp32:esp32:"        ]]; then
            arduino-cli compile -e -b $BOARD $PWD/software/firmware/source/SoftRF ;
          fi ;
          if [[ "$BOARD" =~ "adafruit:nrf52:"      ]]; then
            arduino-cli compile -e -b $BOARD $PWD/software/firmware/source/SoftRF ;
          fi ;
